### ISSUE TITLE
Move base package list to group_vars

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/ansible-role-linux#5]
We want to allow for hosts to customize the base package list.  The packages should not be hard coded in the role.  For instance, we now have a line for VM-tools; however, we use this on physical machines as well.

We should be able to customize the base packages.

**Comment by charlesbrandt** [comment]
Are you referring to the group_vars associated with the role or with the inventory?

I would prefer to put only those items that are not universal in the group_vars. Moving everything to group_vars makes the playbooks harder to read and less useful for others who may not have access to our inventory.

**Comment by inghamn** [comment]
With the standardization of CKAN uploading, we want to make sure CURL is available on any machines that will be uplolading to CKAN.   We probably don't want  CURL on all linux machines, so it might make sense to put it's declaration in group_vars.

**Comment by inghamn** [comment]
We'll need to remove the custom config files for nano, vim, and tmux.  I expect users will set up their own user-specific config files when they first log into the systems.
